### PR TITLE
Moved to actions, doxygenized

### PR DESCRIPTION
**Pull request by dherrada**

### CODE REVIEW

**Comment by PaintYourDragon** [comment]
This library is specific to the SAMD21 and 51. Setting the test platforms in githubci.yml (and architecture in library.properties if one wants to be strict) should fix the build error.

**Comment by dherrada** [comment]
@PaintYourDragon I'm assuming that just having the 'zero' and the 'metro_m4' is enough, right?

**Comment by PaintYourDragon** [comment]
Not related to the build errors, but just the warnings…in library.properties, I suspect the architectures should just be SAMD (I don’t know if there’s a canonical list of library.properties architectures somewhere).

Not sure what’s up with the EPioType errors, looking at that now.

**Comment by dherrada** [comment]
@PaintYourDragon Thanks for fixing that EPioType issue. I don't think I would have had much of a shot at figuring that one out. 

Also, are you sure this is meant for the SAMD51 as well as the SAMD21? The README says
> PDM microphone library for the Arduino Zero / Adafruit Feather M0 (SAMD21 processor).

**Comment by PaintYourDragon** [comment]
I think it was originally written for SAMD21, with the README reflecting that, and then the 51 came along later (with no edits there). PDM peripheral definitely exists on both devices. Since the examples reference odd hardware registers or SPI peripherals, they were probably written for something specific and didn’t get documented as such.

**Comment by PaintYourDragon** [comment]
Can confirm: compiles on PyBadge and Monster M4sk, those appear to be the only boards with a PDM mic on SPI2.

**Comment by ladyada** [comment]
yay great work, btw @dherrada there's also .uno.test.only file options, when there's only one board to test for a demo!

**Comment by dherrada** [comment]
@ladyada Oh, I did not know that. That seems really useful actually

**Pull request merged**
